services:
  postgres:
    image: postgres:15-alpine
    container_name: order-management-system-postgres
    restart: always
    environment:
      POSTGRES_DB: order-management-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - order-management-system-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  order-management-system-network:
    driver: bridge